version: "3.9"
services:
    mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - '27017:27017'
    api:
      container_name: mocky
      restart: always
      build: .
      ports:
        - "3000:3000"
      links:
        - mongo
